services:
  - type: web
    name: puppeteer-service
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
    build:
      aptDependencies:
        - chromium-browser
        - fonts-liberation
   
